/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DigitOutputPanel.java
 *
 * Created on 22.10.2009, 12:01:45
 */

package de.berlin.fu.inf.pattern.u02.gui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;

import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import org.apache.log4j.Logger;

import de.berlin.fu.inf.pattern.data.SimpleDatabase;
import de.berlin.fu.inf.pattern.u02.data.Digit;
import de.berlin.fu.inf.pattern.u02.data.DigitReader;

/**
 *
 * @author alex
 */
public class DigitOutputPanel extends javax.swing.JPanel implements ListSelectionListener {
	private static final long serialVersionUID = 1L;
	
	private Logger logger = Logger.getLogger(DigitOutputPanel.class);
    private DigitTableModel digitTableModel = new DigitTableModel();

    private DigitDrawingPanel jDrawingPanel = new DigitDrawingPanel();
    
    DigitReader digitRead = new DigitReader();

    SimpleDatabase<Digit, Integer>  simpleDatabase;

    /** Creates new form DigitOutputPanel */
    public DigitOutputPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(digitTableModel);
        jTable1.getSelectionModel().addListSelectionListener(this);
        
        
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTrainingFile = new javax.swing.JTextField();
        jTextFieldTrainingFile.setPreferredSize(new Dimension(160, 20));
        
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTestFile = new javax.swing.JTextField();
        
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jDrawingPanel = new DigitDrawingPanel();
        
        
        
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Learning File:");

        jLabel2.setText("Test File");

        jTextFieldTestFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTestFileActionPerformed(evt);
            }
        });

        jButton1.setText("Learn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Test");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

   

        BorderLayout borderLayout = new BorderLayout();
        
        JPanel jPanelTop = new JPanel(new FlowLayout(FlowLayout.CENTER));
        this.jDrawingPanel.setPreferredSize(new Dimension(200, 200));
        
        
        this.setLayout(borderLayout);
        jPanelTop.add(jLabel1, BorderLayout.NORTH);
        jPanelTop.add(jTextFieldTrainingFile, BorderLayout.NORTH);
        jPanelTop.add(jButton1, BorderLayout.NORTH);
        this.add(jPanelTop, BorderLayout.NORTH);
        //this.add(jLabel2);
        //this.add(jTextFieldTestFile);
        //this.add(jButton2);
        this.add(jScrollPane1, BorderLayout.CENTER);
        this.add(jDrawingPanel, BorderLayout.EAST);
        
        
        
        /*
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTrainingFile, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(jTextFieldTestFile, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTrainingFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTestFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
        );
        */
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTestFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTestFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTestFileActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        final String fileName = this.jTextFieldTrainingFile.getText();

        new Thread (
            new Runnable() {

                public void run() {
                    DigitReader reader = new DigitReader();

                    digitTableModel.setData(reader.readDigits(fileName));
                    jTable1.validate();
                }
            }
        ).start();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldTestFile;
    private javax.swing.JTextField jTextFieldTrainingFile;
    // End of variables declaration//GEN-END:variables

    
    
	public void valueChanged(ListSelectionEvent e) {
		// int index = e.getFirstIndex();
		int index = this.jTable1.getSelectedRow();
		Digit digit = this.digitTableModel.getDigit(index);
		
		logger.debug("Selection: " + digit);
		jDrawingPanel.setDigit(digit);
	}

    

}
