/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainJFrame.java
 *
 * Created on 12.01.2010, 18:50:19
 */

package de.berlin.fu.inf.pattern.tasks.gui;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.border.BevelBorder;
import org.apache.log4j.Logger;

/**
 *
 * @author alex
 */
public class MainJFrame extends javax.swing.JFrame {
    private final Logger logger = Logger.getLogger(MainJFrame.class);

    private JSimplePlot jSimplePlot;
    private TrajectoryController controller;
    private int selectedTrajectory;

    // data

    /** Creates new form MainJFrame */
    public MainJFrame() {
        initComponents();
        postInit();
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPlotContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTrajectories = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trajectory");

        jPlotContainer.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout jPlotContainerLayout = new javax.swing.GroupLayout(jPlotContainer);
        jPlotContainer.setLayout(jPlotContainerLayout);
        jPlotContainerLayout.setHorizontalGroup(
            jPlotContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPlotContainerLayout.setVerticalGroup(
            jPlotContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        jListTrajectories.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListTrajectories.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListTrajectoriesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListTrajectories);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPlotContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
            .addComponent(jPlotContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListTrajectoriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListTrajectoriesValueChanged
        logger.debug("ListSelectionEvent: " +evt);
        int index = this.jListTrajectories.getSelectedIndex();
        logger.debug("selected index = " + index);
        this.showTrajectory(index);
    }//GEN-LAST:event_jListTrajectoriesValueChanged

    private void postInit() {
        jSimplePlot = new JSimplePlot();
        // jSimplePlot.setBackground(Color.WHITE);
        jSimplePlot.setPlotRange(20, 60, 420, 460);
        this.jPlotContainer.setLayout(new BorderLayout());
        this.jPlotContainer.add(jSimplePlot, BorderLayout.CENTER);

        this.selectedTrajectory = -1;
    }

    private void controllerInit() {
        this.jListTrajectories.setListData(
                controller.getTrajectoryDescriptors().toArray(new String[0]));

    }

    public void setTrajectoryController(TrajectoryController controller) {
        this.controller = controller;
        this.controllerInit();
    }

    protected void showTrajectory(final int id) {
        if( this.selectedTrajectory == id ) return;
        
        this.selectedTrajectory = id;
        this.jSimplePlot.setData(controller.getTrajecotryData(id));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jListTrajectories;
    private javax.swing.JPanel jPlotContainer;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
